name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Send files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          source: Docker-TP-4.0--Nest-API
          target: .
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd Docker-TP-4.0--Nest-API
            docker build -t my-nest-api .
            docker run -d -p 3000:3000 my-nest-api
